### ISSUE TITLE
Please add Diffusion loader to sage utils

### ISSUE THREAD

**Issue by tecknight** [arcum42/ComfyUI_SageUtils#1]
Sage utils has basic loaders, but in order to track my Flux images, I would like sage utils to have a custom version of the more commonly used non-simple loaders. At this time I have several Flux checkpoints that I can only use with the Diffusion loader. As I would prefer all my images to have metadata included and I prefer all my checkpoints to be tracked, I request that you add the Diffusion loader and perhaps some of the other non-standard loaders that are more commonly used. Thank you for considering my enhancement request.

**Comment by arcum42** [comment]
I've added one in in the last commit. Please try it out and let me know how well it works.

**Comment by arcum42** [comment]
I''l go ahead and close this for the moment.
